apiVersion: v1
kind: Service
metadata:
  name: hirokei-webapp

spec:
  # どのPodを使うかを指定
  # クラスタ内のポッドに外部(ブラウザ)からアクセスできるようにポートを指定
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: hirokei-queue

spec:
  selector:
    app: queue
    release: '1'

  ports:
    - name: http
      port: 8161
      nodePort: 30020

  type: NodePort
