apiVersion: v1
kind: Service
metadata:
  name: hirokei-webapp

spec:
  # どのPodを使うかを指定
  # クラスタ内のポッドに外部(ブラウザ)からアクセスできるようにポートを指定
  selector:
    app: webapp
    release: '0-5'

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort
